const { MongoClient } = require('mongodb');
const { Pool } = require('pg');
const {
  getNoSqlConnectionString,
  getNoSqlDatabaseName,
  getPostgresConnectionString,
  isSplitStoreEnabled,
} = require('./config');

let pgPool = null;
let mongoClient = null;
let mongoDb = null;

function postgresSslConfig() {
  const sslMode = String(process.env.POSTGRES_SSL || process.env.PGSSLMODE || '').toLowerCase();
  if (sslMode === 'true' || sslMode === 'require') {
    return { rejectUnauthorized: false };
  }
  return undefined;
}

async function ensurePostgresSchema(pool) {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      name TEXT NOT NULL,
      avatar TEXT DEFAULT '',
      bio TEXT DEFAULT '',
      city TEXT DEFAULT '',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS attendance (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      performance_id INTEGER,
      show_id TEXT NOT NULL,
      title_snapshot TEXT DEFAULT '',
      date_time_snapshot TIMESTAMPTZ,
      theatre_name_snapshot TEXT DEFAULT '',
      theatre_city_snapshot TEXT DEFAULT '',
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(user_id, show_id)
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS friend_requests (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      from_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      to_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      status TEXT DEFAULT 'pending' CHECK(status IN ('pending', 'accepted', 'rejected')),
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(from_user_id, to_user_id)
    )
  `);

  await pool.query('CREATE INDEX IF NOT EXISTS idx_attendance_user ON attendance(user_id)');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_attendance_show ON attendance(show_id)');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_friend_requests_from ON friend_requests(from_user_id)');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_friend_requests_to ON friend_requests(to_user_id)');
  await pool.query('CREATE INDEX IF NOT EXISTS idx_friend_requests_status ON friend_requests(status)');
}

async function ensureMongoSchema(db) {
  const theatres = db.collection('theatres');
  const shows = db.collection('shows');
  const scrapeRuns = db.collection('scrape_runs');
  const showChangeEvents = db.collection('show_change_events');

  await theatres.createIndex({ stable_id: 1 }, { unique: true });
  await theatres.createIndex({ osm_id: 1 });
  await theatres.createIndex({ name: 1 });
  await theatres.createIndex({ city: 1 });
  await theatres.createIndex({ province: 1 });

  await shows.createIndex({ show_id: 1 }, { unique: true });
  await shows.createIndex({ theatre_id: 1 });
  await shows.createIndex({ theatre_numeric_id: 1 });
  await shows.createIndex({ date_time: 1 });
  await shows.createIndex({ removed: 1 });
  await shows.createIndex({ status: 1 });
  await shows.createIndex({ genre: 1 });
  await shows.createIndex({ source_event_id: 1 });

  await scrapeRuns.createIndex({ started_at: -1 });
  await showChangeEvents.createIndex({ show_id: 1, created_at: -1 });
}

async function initSplitStore() {
  if (!isSplitStoreEnabled()) return null;

  const postgresUrl = getPostgresConnectionString();
  const mongoUrl = getNoSqlConnectionString();

  if (!postgresUrl) {
    throw new Error('DATA_BACKEND=split requires DATABASE_URL or POSTGRES_URL.');
  }
  if (!mongoUrl) {
    throw new Error('DATA_BACKEND=split requires NOSQL_CONNECTION_STRING or MONGODB_URI.');
  }

  if (!pgPool) {
    pgPool = new Pool({
      connectionString: postgresUrl,
      ssl: postgresSslConfig(),
    });
    await pgPool.query('SELECT 1');
    await ensurePostgresSchema(pgPool);
  }

  if (!mongoClient) {
    mongoClient = new MongoClient(mongoUrl);
    await mongoClient.connect();
    mongoDb = mongoClient.db(getNoSqlDatabaseName());
    await ensureMongoSchema(mongoDb);
  }

  return { pgPool, mongoDb };
}

function getPgPool() {
  if (!pgPool) throw new Error('PostgreSQL pool is not initialized.');
  return pgPool;
}

function getMongoDb() {
  if (!mongoDb) throw new Error('NoSQL database is not initialized.');
  return mongoDb;
}

function getCollections() {
  const db = getMongoDb();
  return {
    theatres: db.collection('theatres'),
    shows: db.collection('shows'),
    scrapeRuns: db.collection('scrape_runs'),
    showChangeEvents: db.collection('show_change_events'),
  };
}

module.exports = {
  getCollections,
  getMongoDb,
  getPgPool,
  initSplitStore,
};
